<?php
/**
 * Created by PhpStorm.
 * User: lacasera
 * Date: 12/23/18
 * Time: 12:19 AM
 */
namespace Lacasera\Emojis;

trait Animals
{
    protected $animals = [
        ':grinning_cat'=>'😺',
        ':grinning_cat_with_smile'=>'😸',
        ':joy_cat' => '😹',
        ':cat_with_heart_eyes' => '😻',
        ':cat_with_wry_smile' =>  '😼',
        ':kissing_cat' => '😽',
        ':weary_cat' => '🙀',
        ':crying_cat' => '😿',
        ':pouting_cat' => '😾',
        ':see_no_evil_monkey' => '🙈',
        ':hear_no_evil_monkey' => '🙉',
        ':speak_no_evil_monkey' => '🙊',
        ':monkey_face' => '🐵',
        ':monkey' => '🐒',
        ':gorilla' => '🦍',
        ':dog_face' => '🐶',
        ':dog' => '🐕',
        ':poddle' => '🐩',
        ':fox' => '🦊',
        ':wolf' => '🐺',
        ':cat_face' => '🐱',
        ':cat' => '🐈',
        ':lion' => '🦁',
        ':tiger_face' => '🐯',
        ':tiger' => '🐅',
        ':leopard' => '🐆',
        ':horse_face' => '🐴',
        ':horse' => '🐎',
        ':unicorn' => '🦄',
        ':zebra' => '🦓',
        ':deer' => '🦌',
        ':cow_face' => '🐮',
        ':ox' => '🐂',
        ':water_buffalo' => '🐃',
        ':cow' => '🐄',
        ':pig_face' => '🐷',
        ':pig' => '🐖',
        ':boar' => '🐗',
        ':pig_nose' => '🐽',
        ':ram' => '🐏',
        ':ewe' => '🐑',
        ':goat' => '🐐',
        ':camel' => '🐪',
        ':two_hump_camel' => '🐫',
        ':giraffe' => '🦒',
        ':elephant' => '🐘',
        ':rhinoceros' => '🦏',
        ':mouse_face' => '🐭',
        ':mouse' => '🐁',
        ':rat' => '🐀',
        ':hamster' => '🐹',
        ':rabbit_face' => '🐰',
        ':rabbit' => '🐇',
        ':chipmunk' => '🐿',
        ':hedgehog' => '🦔',
        ':bat' => '🦇',
        ':bear' => '🐻',
        ':koala' => '🐨',
        ':panda' => '🐼',
        ':paw_print' => '🐾',
        ':turkey' => '🦃',
        ':chicken' => '🐔',
        ':rooster' => '🐓',
        ':hatching_chick' => '🐣',
        ':baby_chick' => '🐤',
        ':front_facing_baby_chick' => '🐥',
        ':bird' => '🐦',
        ':penguin' => '🐧',
        ':dove' => '🕊',
        ':eagle' => '🦅',
        ':duck' => '🦆',
        ':owl' => '🦉',
        ':frog' => '🐸',
        ':crocodile' => '🐊',
        ':turtle' => '🐢',
        ':lizard' => '🦎',
        ':snake' => '🐍',
        ':dragon_face' => '🐲',
        ':dragon' => '🐉',
        ':sauropod' => '🦕',
        ':t_rex' => '🦖',
        ':spouting_whale' => '🐳',
        ':whale' => '🐋',
        ':dolphin' => '🐬',
        ':fish' => '🐟',
        ':tropical_fish' => '🐠',
        ':blow_fish' => '🐡',
        ':shark' => '🦈',
        ':octopus'=> '🐙',
        ':spiral_shell' => '🐚',
        ':snail' => '🐌',
        ':butterfly' => '🦋',
        ':bug' => '🐛',
        ':ant' => '🐜',
        ':honeybee' => '🐝',
        ':lady_beetle' => '🐞',
        ':cricket' => '🦗',
        ':spider' => '🕷',
        ':spider_web' => '🕸',
        ':scorpion' => '🦂'
    ];
}