<?php
namespace Lacasera\Emojis;

trait Faces
{
    protected $faces =  [
        ':smile' =>'😀', ':wink' =>'😁', ':joy'=>'😂',
        ':rolling_on_the_floor_laughing'=>'🤣',
        ':grinning_face_with_big_eyes' => '😃',
        ':grinning_face_with_smiling_eyes'=>'😄',
        ':grinning_face_with_sweat'=>'😅',
        ':grinning_squinting_face'=>'😆',
        ':winking_face'=>'😉',
        ':smiling_face_with_smiling_eyes'=>'😊',
        ':yum'=>'😋',
        ':sunglasses'=>'😎',
        ':heart_eyes'=>'😍',
        ':kissing_heart'=>'😘',
        ':kissing'=>'😗',
        ':kissing_simley_eyes'=>'😙',
        ':kissing_closed_eyes'=>'😚',
        ':slightly_smiling_face'=>'️🙂',
        ':hugging_face'=>'🤗',
        ':star_stuck'=>'🤩',
        ':thinking_face'=>'🤔',
        ':face_with_raised_eyebrow'=>'🤨',
        ':neutral_face'=>'😐',
        ':expressionless'=>'😑',
        ':no_mouth'=> '😶',
        'face_with_rolling_eyes'=>'🙄',
        ':smirk'=>'😏',
        ':persevere'=>'😣',
        ':disappointed_relieved'=>'😥',
        ':open_mouth'=>'😮',
        ':zipper_mouth_face'=>'🤐',
        ':hushed'=>'😯',
        ':sleepy'=>'😪',
        ':tired_face'=>'😫',
        ':sleeping' => '😴',
        ':relieved'=>'😌',
        ':stuck_out_tongue'=>'😛',
        ':stuck_out_tongue_winking'=>'😜',
        ':stuck_out_tongue_closed_eye'=>'😝',
        ':drolling_face'=>'🤤',
        ':unamused'=>'😒',
        ':sweat'=>'😓',
        ':pensive'=>'😔',
        ':confused'=>'😕',
        ':upside_down_face'=>'🙃',
        ':money_mouth_face'=>'🤑',
        ':astonished'=>'😲',
        ':white_frowning_face'=>'️🙁',
        ':slightly_frowning_face'=>'😖',
        ':confounded'=>'😞',
        ':disappointed'=>'😟',
        ':triumph'=>'😤', ':cry'=>'😢', ':sob'=>'😭',
        ':frowning'=>'😦',':anguished'=>'😧',':fearful'=>'😨',
        ':weary'=>'😩',':exploded_head'=>'🤯',':grimacing'=>'😬',
        ':cold_sweat'=>'😰', ':scream'=>'😱', ':flushed'=>'😳',
        ':zany_face'=>'🤪', ':dizzy_face' => '😵',
        ':rage'=>'😡',':angry'=>'😠','face_with_symbols_on_mouth'=>'🤬',
        ':mask'=>'😷',':face_with_thermometer'=>'🤒',
        ':face_with_head_bandage'=>'🤕',':nauseated_face'=>'🤢',
        ':face_vomiting'=>'🤮',':sneezing_face'=>'🤧',
        ':innocent'=>'😇', ':cowboy_face'=> '🤠', ':clown_face'=>'🤡',
        ':lying_face'=>'🤥', ':shusing_face'=>'🤫',
        ':face_with_hand_over_mouth'=>'🤭',
        ':face_with_monocle'=>'🧐',
        ':nerd_face'=>'🤓',
        ':skull' => '💀',
        ':skull_crossbones' => '☠'
    ];
}